### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Yasukii** [PatrickSantoZZ/infinity-journal#2]
Is there a way to fix this?

![TERA_2019-10-24_00-42-24](https://user-images.githubusercontent.com/34219032/67439669-35cf0e00-f5f7-11e9-8fc4-2967e3af2bc8.png)

**Comment by PatrickSantoZZ** [comment]
sure , i rework the mod in the next 1-2 month. you can use owny's version in this time. its fully working you just need to switch your "journal.json" from my version to Owyn's Version.
